FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common ./common
COPY applier ./applier
COPY config ./config
COPY data ./data

CMD ["python", "-m", "applier.run"]

